FROM python:3.11-slim

WORKDIR /app

# Устанавливаем зависимости
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем всё остальное
COPY . .

# Открываем порт FastAPI
EXPOSE 8001

# Запускаем с перезагрузкой при изменениях
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]